### ISSUE TITLE
Standard logging module

### ISSUE THREAD

**Issue by loicbachelot** [CMCC-Foundation/bluecloud-mockup_method#1]
Using the python logging module we can format the logs as we want: [logging module doc](https://docs.python.org/3.8/library/logging.html)

I attached an example
[oceanpatterns.log](https://github.com/CMCC-Foundation/bluecloud-mockup_method/files/6507316/oceanpatterns.log)

Let me know if that could work with the requirements of the logs

**Comment by mdrudi** [comment]
This looks actually useful for the "exec_info" section

**Comment by anto6715** [comment]
> Using the python logging module we can format the logs as we want: [logging module doc](https://docs.python.org/3.8/library/logging.html)
> 
> I attached an example
> [oceanpatterns.log](https://github.com/CMCC-Foundation/bluecloud-mockup_method/files/6507316/oceanpatterns.log)
> 
> Let me know if that could work with the requirements of the logs

This log is well structured, but if you provide this at the web interface it's hard to understand if there's an error and the type of error.

To understand better the reason of json log file:

If the method in dataminer crashes for any reason, the output files will not be produced, so the wps protocol will fail and the only file returned will be the dataminer log which can be very long and hard to read.

To provide a feedback to the web app also in case of a method error, I choose to group the code in some try-catch blocks, in this way each portion of code has a specific error code.
If you do this, when there's an error in the code, you are able to handle the error simply providing some empty file to wps protocol to respect the output interface, then you can add the error code in the json file to notify the web app that an error has occurred and also the type of error plus a small attached message.

If the log in a json file, the web app can immediately read the error code to understand if there were errors or if the method was executed correctly.

Maybe as @mdrudi suggested, we can put that python log into exec_info section

**Comment by loicbachelot** [comment]
Ok, this is clearer to me now. So I will use the JSON format of the logs at least for error handling and see how I can reuse the rest in the "exec_info" section.

**Comment by mdrudi** [comment]
Yes it sounds good. The standard logging module looks very useful to manage the content of the current "exec_info" inside the JSON. For what concerns the other information into the JSON, hopefully in the near future we should do a review of this content, also because of the catalogue, but now it is too early for this kind of activity.

**Comment by mdrudi** [comment]
any action here on CMCC side ?

**Comment by anto6715** [comment]
> any action here on CMCC side ?

no

**Comment by mdrudi** [comment]
@loicbachelot, can we close this ? or something to add ?

**Comment by loicbachelot** [comment]
I think we can close this for now and open it again when it is time to work on unifying the logs with the logs from the data miner.
