### ISSUE TITLE
Datasets not available on WEkEO

### ISSUE THREAD

**Issue by anto6715** [CMCC-Foundation/bluecloud-mockup_method#16]
@mdrudi We have some problems related to the dataset available on WEkEO. 
Currently the product **MEDSEA_MULTIYEAR_PHY_006_004** is no more avaiable.

If a try to search it on WEkEO it seems to return to me the right product but when I try to open it I can see this dataset: **MEDSEA_MULTIYEAR_PHY_006_004-statics_202105**.

Then, if a try to download the monthly temperature dataset using the download module I receive this error:

```
Error: Unexpected response <Response [500]>
Error: Unexpected response <Response [404]>
```

How should we proceed since the high instability of this service in the last month?

**Comment by anto6715** [comment]
This issue stop me also to continue the test of the download module, because this problem regards also other dataset, for example **MEDSEA_MULTIYEAR_WAV_006_012** (one of the new dataset that I should introduce)

**Comment by mdrudi** [comment]
To keep in mind, the products we are targetting now are:

- MEDSEA_MULTIYEAR_PHY_006_004
- GLOBAL_REANALYSIS_PHY_001_030
- OCEANCOLOUR_MED_BGC_L4_MY_009_144 (replacing OCEANCOLOUR_MED_CHL_L4_REP_OBSERVATIONS_009_078)
- MEDSEA_MULTIYEAR_WAV_006_012

**Comment by mdrudi** [comment]
consistency with 

https://github.com/CMCC-Foundation/bluecloud-mockup_method/blob/6682236bfe2e4dda3460a393918471b17b1b1d6f/download/config/dataset_infrastructures.json#L1-L29

**Comment by mdrudi** [comment]
Note here https://github.com/CMCC-Foundation/bluecloud-mockup_method/pull/15#issuecomment-1191568351

**Comment by mdrudi** [comment]
https://help.marine.copernicus.eu/en/articles/5151127-how-to-consume-the-motu-rest-api-and-cas-sso
https://help.marine.copernicus.eu/en/articles/4796533-what-are-the-motu-client-motuclient-and-python-requirements

**Comment by anto6715** [comment]
20220829 UPDATE

- **MEDSEA_MULTIYEAR_PHY_006_004**: on WEkEO site it is available only in a specific date 16/05/2020 
- **OCEANCOLOUR_MED_BGC_L4_MY_009_144**: doesn't return a netCDF4 files but a dods (?) file

**Comment by mdrudi** [comment]
> 20220829 UPDATE
> 
>     * **MEDSEA_MULTIYEAR_PHY_006_004**: on WEkEO site it is available only in a specific date 16/05/2020
> 
>     * **OCEANCOLOUR_MED_BGC_L4_MY_009_144**: doesn't return a netCDF4 files but a dods (?) file

...per la tabella di report che chiedevo questa mattina, va bene anche se la scrivi qui. Pero' avrei bisogno che mi indicassi anche il CF standard name del campo che si tenta di accedere
