### ISSUE TITLE
[SSI] Alternative to fromisodateformat() in python 3.6

### ISSUE THREAD

**Issue by anto6715** [CMCC-Foundation/bluecloud-mockup_method#18]
Here an alternative function that can be tested as alternative of datetime.date.fromisodateformat():

```
def string_to_iso_date(date, default_month=None, default_day=None, default_hours=None):
    """
    This function read a date as string and return it in ISO format.
    Only year in strin date in mandatory, the others parameters are set to a defualt
    value if missing.
    It's possible to set the default value for month, day and hours
    @param date: A date in string format
    @param default_month: A value to set if month is not present on date
    @param default_day: A value to set if day is not present on date
    @param default_hours: A value to set if  hours is not present on date
    @return: date in ISO format: YYYY-MM-ddThh:mm:ss
    """
    import dateutil.parser as parser
    YYYY = 1
    MM = default_month if default_month is not None else 1
    dd = default_day if default_day is not None else 1
    hh = default_hours if default_hours is not None else 0
    mm = 0
    ss = 0

    return parser.parse(date, default=datetime.datetime(YYYY, MM, dd, hh, mm, ss))
```

The function return a datetime python object

**Comment by anto6715** [comment]
problem solved using a different solution

**Comment by noteboom** [comment]
Hi @anto6715 

Just after I implemented my solution I found out about your alternative solution...... In my solution I the dates format must be specified as YYYY-MM-dd  (Not sure what happens if another format is used e.g. that includes HH : mm

**Comment by anto6715** [comment]
> Hi @anto6715
> 
> Just after I implemented my solution I found out about your alternative solution...... In my solution I the dates format must be specified as YYYY-MM-dd (Not sure what happens if another format is used e.g. that includes HH : mm

My solution return a datetime object, that I suppose that you are free to print it in the format that you prefer. But if you already have a working solution, don't worry about this issue.
