### ISSUE TITLE
[SSI] Prepare mock files to return in case of error

### ISSUE THREAD

**Issue by anto6715** [CMCC-Foundation/bluecloud-mockup_method#19]
Hi @noteboom,

as you already implemented in your code, in case of error we call:

https://github.com/CMCC-Foundation/bluecloud-mockup_method/blob/4ef7f95ce73e28fdf95dfd5c9646393ed3c6b5dc/log/logmng.py#L76

This function, is used to finalize the method in case of error. 
In case of error, the most important thing to do is to provide to WPS the expected output files declared in the method interface (in software importer). If the outputs are present, also in case of error the web interface will be able to download the log data in order to have an information of the status of the execution ( or the message error).

To do this, it is sufficient to prepare some empty files with the same name of the expected output and then copy that file in the root directory in case of error. The handle_exec function already do this but with the OceanClimate outputs, as you can see here:

https://github.com/CMCC-Foundation/bluecloud-mockup_method/blob/4ef7f95ce73e28fdf95dfd5c9646393ed3c6b5dc/log/logmng.py#L91-L92

For your method, I suggest to create the mock directory and put here two output files with the same name of the expected ones (they can be also empty) and to update these two lines of codes in order to provide them in case of error

**Comment by noteboom** [comment]
Hi @anto6715 

Thanks for your message. I will update the SSI method accordingly.

Best regards,
JW

**Comment by noteboom** [comment]
Hi @anto6715 

The method now SSI_output.nc and SSI_area_timeseries.png (and output.json) as the output files... Should I changed this to output.nc and output.png (and output.json) in the SSI software and  method parameters?

JW

**Comment by anto6715** [comment]
> Hi @anto6715
> 
> The method now SSI_output.nc and SSI_area_timeseries.png (and output.json) as the output files... Should I changed this to output.nc and output.png (and output.json) in the SSI software and method parameters?
> 
> JW

No, the name must remains the same of your method. Here the code in your case:

```
shutil.copy("./mock/SSI_output.nc", "SSI_output.nc")
shutil.copy("./mock/SSI_area_timeseries.png", "SSI_area_timeseries.png")
```
