### ISSUE TITLE
Add timeout and print response when status fails

### ISSUE THREAD

**Issue by anto6715** [CMCC-Foundation/bluecloud-mockup_method#2]
As @loicbachelot suggests:

1. Add a timeout as exit condition in (2 minutes should be enough):

https://github.com/CMCC-Foundation/bluecloud-mockup_method/blob/fc9efaa1ec9e3c224a337dfbad4468d442b3471f/download/wekeo/functions.py#L205

2. add 'json.loads(response.text)['message']' to log when the status is fail

**Comment by anto6715** [comment]
>     2. add 'json.loads(response.text)['message']' to log when the status is fail

I think it's better to raise an exception that reads the error message from `json.loads(response.text)['message']`, the exception will be caught by the try-catch in the mockup that prints the message and adds it in the log file

**Comment by loicbachelot** [comment]
> > ```
> > 2. add 'json.loads(response.text)['message']' to log when the status is fail
> > ```
> 
> I think it's better to raise an exception that reads the error message from `json.loads(response.text)['message']`, the exception will be caught by the try-catch in the mockup that prints the message and adds it in the log file

Yes, that seems like a perfect solution! The wekeo error message is clear enough to be used as-is.
In the case the request fails, what would be the ideal handling? Exit the method and still create all the output files?

**Comment by anto6715** [comment]
> In the case the request fails, what would be the ideal handling? Exit the method and still create all the output files?

Yes, we use this approach:
When there is an error, the method creates all output files (also empty files are ok), then put the right error code in the json and then exit correctly.

Then, to know the result of the method you have to read the error.code in json file.
If the error.code = 0 it means that the execution is ok, otherwise the code indicates the type of error (for example -1 indicates a problem with the format of input_parameters string, -2 an error in download procedure and so on)

**Comment by anto6715** [comment]
With the last commit I added a check if the status is failed, in that case the code raise an Exception try to print the message received.

I added also a 2 minute timeout.

Let me know it is all ok

**Comment by loicbachelot** [comment]
After the 2 fixes, everything is working for me both using a key or the proxy. Thanks!
