### ISSUE TITLE
Fix spatial and time domain for C3S_ERA5_MEDSEA_1979_2020_STHUB 

### ISSUE THREAD

**Issue by anto6715** [CMCC-Foundation/bluecloud-mockup_method#20]
Hi @noteboom, we found the error reported here: https://github.com/CMCC-Foundation/bluecloud-mockup_method/issues/20#issuecomment-1293479548. 
can you please provide us the right information about longitude, latitude and time range for your dataset?

Currently there are these info in the mockup:
https://github.com/CMCC-Foundation/bluecloud-mockup_method/blob/7b86159e8c6b5dd3cacad43672cf80fe57d04d77/download/config/sthub_dataset.json#L12-L14

**Comment by anto6715** [comment]
FYI @gottomondo

**Comment by anto6715** [comment]
Here the string that generate an error:


`{'id_output_type':'ssi_percentile_min','data_source':['C3S_ERA5_MEDSEA_1979_2020_STHUB'],'title':'Title','time_stepsize':1,'time_stepunit':'Years','threshold_perc':'P98','start_time':'1979-01-01','end_time':'1980-12-01','working_domain':{'box':[[-4.99,34,1,42]]},'id_field':'none'}`

and here the error message that we got:

`Exception: Start latitude 1 outside input lat. RANGE: 30.0 till 46.0`

I think that there is an error when the method try to read working domain. Here the correct format: box: [min lon, min lat, max lon, max lat ]
If we consider 'box':[[-4.99,34,1,42]], from the error message it seems that the method read 1 value as min lat and not as max lon

**Comment by anto6715** [comment]
> Here the string that generate an error:
> 
> `{'id_output_type':'ssi_percentile_min','data_source':['C3S_ERA5_MEDSEA_1979_2020_STHUB'],'title':'Title','time_stepsize':1,'time_stepunit':'Years','threshold_perc':'P98','start_time':'1979-01-01','end_time':'1980-12-01','working_domain':{'box':[[-4.99,34,1,42]]},'id_field':'none'}`
> 
> and here the error message that we got:
> 
> `Exception: Start latitude 1 outside input lat. RANGE: 30.0 till 46.0`
> 
> I think that there is an error when the method try to read working domain. Here the correct format: box: [min lon, min lat, max lon, max lat ] If we consider 'box':[[-4.99,34,1,42]], from the error message it seems that the method read 1 value as min lat and not as max lon

Currently the working domain of input parameters string is different from download module:

https://github.com/CMCC-Foundation/bluecloud-mockup_method/blob/7b86159e8c6b5dd3cacad43672cf80fe57d04d77/download/daccess.py#L72

I think that this is the cause of this misunderstanding

**Comment by anto6715** [comment]
Hi @noteboom, I think that you write https://github.com/CMCC-Foundation/bluecloud-mockup_method/issues/21#issuecomment-1294837788 in the wrong issue.


Then, from your answer, we agree about the problem. 
That said, is it feasible to use the format of MEI generator in SSI method? That is the format used in the others method (and then in MEI generator app). Obviously it need an update also on the document (sorry if I didn't noticed until now)

Thanks

**Comment by noteboom** [comment]
No problem, I will update the SSI method.  I will let you know when this has been completed

**Comment by noteboom** [comment]
Fixed, uploaded (GitHub) and updated SSI04 method. Checked (it works)

**Comment by anto6715** [comment]
> Fixed, uploaded (GitHub) and updated SSI04 method. Checked (it works)

Great.
A last question, what about for the lon/lat/time range indicated in https://github.com/CMCC-Foundation/bluecloud-mockup_method/issues/20#issue-1425561771)? 

Time range should be 1979-2020 if I remember well, instead I need your approval about lon lat range in order to ask the right domain to the users

**Comment by noteboom** [comment]
Latitude 30.0 to 46.0
Longitude -6.0 to 36.0
Time 1 January 1979 till 31 December 2020 

Please use also different defaults e.g 
Lat: 32.0 - 44.0,
Long:  -6 to 36.0
Sstart_time': '1990-01-01' and end_time': '2019-12-31  ...... **However, I could not  specify the day in the MEI generator!ot not specify the day in the MEI generator!**

**Comment by anto6715** [comment]
> Please use also different defaults e.g
> Lat: 32.0 - 44.0,
> Long: -6 to 36.0

@gottomondo It is possible to set these value as  default when the parameters are shown to the user?

> **However, I could not specify the day in the MEI generator**

The user should be able to select the day in the time range when the Time Step unit is equal to Days or in any case?

**Comment by anto6715** [comment]
The time and spatial domain is correct on the mei-generator, also the default values have been set correctly.

If any, other issue will be discussed in specific issue, this has been completed
