### ISSUE TITLE
Execption during error handling

### ISSUE THREAD

**Issue by anto6715** [CMCC-Foundation/bluecloud-mockup_method#21]
Hi @noteboom, it seems that there are a problem with a mock file in your method. When an error is raised, in the log we have another error:

`FileNotFoundError: [Errno 2] No such file or directory: './mock/SSImaps.png'`

Maybe the file SSImaps.png is missing or the name it is wrong. With this error the method doesn't provide all the necessary output files to the web app and we can't obtain any log.
Can you please check it? 

Thanks

**Comment by anto6715** [comment]
Another execption occurs in the error handling:

```
Traceback (most recent call last):
  File "SSI.py", line 53, in main
    calculateSSI(input_parametersSSI, json_log)  
  File "/home/gcube/wps_config/ecocfg/rscr_cc2a75da-94b3-47aa-b85a-3385f375bba3/SSImethod_4/SSI/SSI_calculation.py", line 280, in calculateSSI
    json_log.handle_exc(traceback.format_exc(), str(e), error_code)
NameError: name 'traceback' is not defined
```

Here should be sufficient to add `import traceback` at the start of the file

**Comment by noteboom** [comment]
The MEI generator for method SSI  convert the (default) input area Lat: 34 - 42 and Long: -4.99 - 1   into box  [-4.99,34,1,42] but the SSI calculation expects [-4.99, 1, 34, 42]   ([min_lon, max_lon, min_lat, max_lat]). See doc: https://docs.google.com/document/d/1oLvM1l2cvpJNCif9k91_OBMzrgS5SE1X/edit#heading=h.gjdgxs

**Comment by noteboom** [comment]
Sorry, I had not checked that issue.

**Comment by noteboom** [comment]
Something strange has happened  to the (zero size) png output files in /mock.  (SSImaps.png and SSI timeseries.png) . They were included in the zip archive but seem to have disappered after unzip....... Anyway I will release a new method  that fixes  the lat/long problem and will then also include these png files again

**Comment by anto6715** [comment]
> Something strange has happened to the (zero size) png output files in /mock. (SSImaps.png and SSI timeseries.png) . They were included in the zip archive but seem to have disappered after unzip....... Anyway I will release a new method that fixes the lat/long problem and will then also include these png files again

If I remember well I had the same issue, it seems that the VRE doesn't allow us to upload empty files.
Maybe the quicker solution is to create directly an empty file using `open(filename, 'w')` command

**Comment by noteboom** [comment]
Added empty png files to method. Fixed problem

**Comment by anto6715** [comment]
Thanks, then the problem is solved.
I'm closing the issue
