### ISSUE TITLE
Uniformity in output.json file name in software importer

### ISSUE THREAD

**Issue by anto6715** [CMCC-Foundation/bluecloud-mockup_method#22]
Hi @noteboom , from our tests we find out that is it very important the name assigned to the output files. In particular we need to use the same nomenclature for the common output files.

Currently the only common output file between the method is the **output.json** log file.
In the software import, you should use the name **out_log**, in order to allow the web app the right access to this file. 
To do this update, you can directly open your method in software importer and change the name of this output

**Comment by noteboom** [comment]
OK, I will use out_log. Thanks

**Comment by anto6715** [comment]
> OK, I will use out_log. Thanks

Thanks to you. 
Please write here when the method has been updated, thanks

**Comment by noteboom** [comment]
Updated SSI04 method. (uses now out_log as parameter name)

**Comment by anto6715** [comment]
Thank you
