### ISSUE TITLE
Python 3.6 compatibility

### ISSUE THREAD

**Issue by loicbachelot** [CMCC-Foundation/bluecloud-mockup_method#3]
In the data miner we are in python 3.6 but we are using
`from __future__ import annotations`
used in `download/daccess.py` and this is only available from 3.7.

**Comment by mdrudi** [comment]
Or is it feasible to review the source code in daccess coming from WEkEO, without big effort ? @anto6715 what do you think ?

**Comment by anto6715** [comment]
Thanks @loicbachelot, that was an old unused import, I removed it
