### ISSUE TITLE
config file wekeo_dataset.json

### ISSUE THREAD

**Issue by loicbachelot** [CMCC-Foundation/bluecloud-mockup_method#5]
Hi @anto6715 ,

I have a question concerning the config file wekeo_dataset.json and more precisely about how you got the 'lat' and 'lon' arrays? 
For the dataset OCEANCOLOUR_MED_CHL_L4_NRT_OBSERVATIONS_009_041 this domain seems to be missing values as on wekeo it is defined between lat: 30/46 and lon: -6/36.5 but only lat:36.5/46 and lon: -6/30. 
I am not sure how to get the missing values, I can't find the exhaustive list on wekeo.
Thanks,

Loïc

**Comment by anto6715** [comment]
HI @loicbachelot, WEkEO doesn't provide this information, this is because I have to put it in this configuration file.

To get these values, I extract them directly from a netCDF file that I previously downloaded with the full domain.
This procedure is not optimal but I haven't found any alternatives at the moment.

About the missing value, there is a strange behavior with this dataset. Both WEkEO and the metadata say that the lon range is -6/36.5 and lat is 30/46, but if I request this full domain, the file wil contain only the domain between lon -6/30 and lat 36.5/46.

I don't know if there were some problems when I downloaded the dataset.

**Comment by mdrudi** [comment]
downloading from CMEMS it looks ok 
https://resources.marine.copernicus.eu/?option=com_csw&view=details&product_id=OCEANCOLOUR_MED_CHL_L4_NRT_OBSERVATIONS_009_041

Is it a specific issue when tring to download this product from WEkEO  ?

**Comment by anto6715** [comment]
> downloading from CMEMS it looks ok
> https://resources.marine.copernicus.eu/?option=com_csw&view=details&product_id=OCEANCOLOUR_MED_CHL_L4_NRT_OBSERVATIONS_009_041
> 
> Is it a specific issue when tring to download this product from WEkEO ?

Yes, I retry to download from WEkEO and there's still the problem.

WEkEO API:
```
ncdump -v lon 202007_mm-HDA--CHLA-Mfs-MED_re.nc
...
data:

 lon = -5.993576, -5.980729, -5.967881, -5.955033, -5.942185, -5.929338,
...
  29.87704, 29.88989, 29.90274, 29.91558, 29.92843, 29.94128, 29.95413, 
    29.96697, 29.97982 ;
}
```

From link in https://github.com/CMCC-Foundation/bluecloud-mockup_method/issues/5#issuecomment-862296961 : 
```
ncdump -v lon dataset-oc-med-chl-multi-l4-chl_1km_monthly-rt-v02_1623845418733.nc
...
data:

 lon = -5.993576, -5.980729, -5.967881, -5.955033, -5.942185, -5.929338,
...
  36.44218, 36.45503, 36.46788, 36.48073 ;
}
```

**Comment by anto6715** [comment]
From the json request I can see that all domain is correctly requested:
```
{
    "datasetId": "EO:MO:DAT:OCEANCOLOUR_MED_CHL_L4_NRT_OBSERVATIONS_009_041:dataset-oc-med-chl-multi-l4-chl_1km_monthly-rt-v02",
    "boundingBoxValues": [
        {
            "name": "bbox",
            "bbox": [
                -6,
                36.4962,
                29.99267,
                45.99494
            ]
        }
    ],
    "dateRangeSelectValues": [
        {
            "name": "position",
            "start": "2020-07-01T00:00:00",
            "end": "2020-07-31T00:00:00"
        }
    ],
    "multiStringSelectValues": [
        {
            "name": "variable",
            "value": [
                "CHL"
            ]
        }
    ],
    "stringChoiceValues": [
        {
            "name": "service",
            "value": "OCEANCOLOUR_MED_CHL_L4_NRT_OBSERVATIONS_009_041-TDS"
        },
        {
            "name": "product",
            "value": "dataset-oc-med-chl-multi-l4-chl_1km_monthly-rt-v02"
        }
    ]
}
```

**Comment by loicbachelot** [comment]
I downloaded from the wekeo website directly and it seems like the bbox is inverted:
```
{
  "datasetId": "EO:MO:DAT:OCEANCOLOUR_MED_CHL_L4_NRT_OBSERVATIONS_009_041:dataset-oc-med-chl-olci_a-l4-chl_1km_monthly-rt-v02",
  "boundingBoxValues": [
    {
      "name": "bbox",
      "bbox": [
        -6,
        29.99267,
        36.4962,
        45.99494
      ]
    }
  ],
  "dateRangeSelectValues": [
    {
      "name": "position",
      "start": "2020-01-01T00:00:00.000Z",
      "end": "2020-01-02T00:00:00.000Z"
    }
  ],
  "multiStringSelectValues": [
    {
      "name": "variable",
      "value": [
        "CHL"
      ]
    }
  ],
  "stringChoiceValues": [
    {
      "name": "service",
      "value": "OCEANCOLOUR_MED_CHL_L4_NRT_OBSERVATIONS_009_041-TDS"
    },
    {
      "name": "product",
      "value": "dataset-oc-med-chl-olci_a-l4-chl_1km_monthly-rt-v02"
    }
  ]
}

**Comment by loicbachelot** [comment]
> To get these values, I extract them directly from a netCDF file that I previously downloaded with the full domain.
> This procedure is not optimal but I haven't found any alternatives at the moment.

What would be the behavior if we just skipped that check? Doesn't it automatically take the closest value on the wekeo side? For example on the website I created the following request bbox for the dataset (and actually showed like this in the API request):

```
"bbox": [
        -8,
        28,
        38,
        40
]"
```
And I got the following values:
lon:  -5.994 / 36.49
lat: 30.01/40.0

**Comment by anto6715** [comment]
> > To get these values, I extract them directly from a netCDF file that I previously downloaded with the full domain.
> > This procedure is not optimal but I haven't found any alternatives at the moment.
> 
> What would be the behavior if we just skipped that check? Doesn't it automatically take the closest value on the wekeo side? For example on the website I created the following request bbox for the dataset (and actually showed like this in the API request):
> 
> ```
> "bbox": [
>         -8,
>         28,
>         38,
>         40
> ]"
> ```
> 
> And I got the following values:
> lon: -5.994 / 36.49
> lat: 30.01/40.0

The closest value isn't the right value.
For example you requested lon max equal to 38, but the file contains 36.49 as max value.

For example, when I request max_lon, I want to receive the **smallest value that contains** my max_lon, only in this way I'm sure that the file contains the coordinates that I requested.

To be more clear, if I request lon: -5.994 / 10, WEkEO can return the range -5.994/9.988891 instead the right interval -5.994/10.00174

**Comment by anto6715** [comment]
> I downloaded from the wekeo website directly and it seems like the bbox is inverted

Right, I didn't noticed that.

@mdrudi @loicbachelot To solve this we have two possibility:
1. Wright at the start the right order for working domain -> this means that we must remember the right order for each dataset
2. Save in the config file the "template" of the working domain for each dataset. In this way the initial working domain remains the same for each processing, then reading this template the code will know how to order the working domain in the json. The template will be in the form: 
` "lonLat_template": "[min_lon, max_lon, min_lat, max_lat]"` .

**Comment by loicbachelot** [comment]
> The closest value isn't the right value.
> For example you requested lon max equal to 38, but the file contains 36.49 as max value.
> 
> For example, when I request max_lon, I want to receive the **smallest value that contains** my max_lon, only in this way I'm sure that the file contains the coordinates that I requested.
> 
> To be more clear, if I request lon: -5.994 / 10, WEkEO can return the range -5.994/9.988891 instead the right interval -5.994/10.00174

In my example, most of the values are outside of the BBox and this is why wekeo is taking smaller. But I understand that in our case shouldn't take the closest value in the dataset but we need the closest containing the value requested (if inside the domain of definition).

**Comment by loicbachelot** [comment]
> > I downloaded from the wekeo website directly and it seems like the bbox is inverted
> 
> Right, I didn't noticed that.
> 
> @mdrudi @loicbachelot To solve this we have two possibility:
> 
> 1. Wright at the start the right order for working domain -> this means that we must remember the right order for each dataset
> 2. Save in the config file the "template" of the working domain for each dataset. In this way, the initial working domain remains the same for each processing, then reading this template the code will know how to order the working domain in the json. The template will be in the form:
>    ` "lonLat_template": "[min_lon, max_lon, min_lat, max_lat]"` .

I think all working domains are defined the same: [min_lon, min_lat, max_lon, max_lat] so this shouldn't be an issue? I tried the following products and they all follow this logic:

- MEDSEA_MULTIYEAR_PHY_006_004
- GLOBAL_ANALYSIS_FORECAST_PHY_001_024
- OCEANCOLOUR_MED_CHL_L4_NRT_OBSERVATIONS_009_041

I requested again the full domain directly from the website and added the lon/lat values into the wekeo_dataset.json file. (I am pushing this update)
Now it is working correctly again!

I think this is solved then, but we have to be careful the order of the working domain is the same for all datasets.

**Comment by anto6715** [comment]
> > > I downloaded from the wekeo website directly and it seems like the bbox is inverted
> > 
> > 
> > Right, I didn't noticed that.
> > @mdrudi @loicbachelot To solve this we have two possibility:
> > 
> > 1. Wright at the start the right order for working domain -> this means that we must remember the right order for each dataset
> > 2. Save in the config file the "template" of the working domain for each dataset. In this way, the initial working domain remains the same for each processing, then reading this template the code will know how to order the working domain in the json. The template will be in the form:
> >    ` "lonLat_template": "[min_lon, max_lon, min_lat, max_lat]"` .
> 
> I think all working domains are defined the same: [min_lon, min_lat, max_lon, max_lat] so this shouldn't be an issue? I tried the following products and they all follow this logic:
> 
>     * MEDSEA_MULTIYEAR_PHY_006_004
> 
>     * GLOBAL_ANALYSIS_FORECAST_PHY_001_024
> 
>     * OCEANCOLOUR_MED_CHL_L4_NRT_OBSERVATIONS_009_041
> 
> 
> I requested again the full domain directly from the website and added the lon/lat values into the wekeo_dataset.json file. (I am pushing this update)
> Now it is working correctly again!
> 
> I think this is solved then, but we have to be careful the order of the working domain is the same for all datasets.

Yes now it's work correctly, thanks

**Comment by anto6715** [comment]
Hi @loicbachelot, can we close this issue?
