### ISSUE TITLE
daccess module can download only one monthly file at time

### ISSUE THREAD

**Issue by anto6715** [CMCC-Foundation/bluecloud-mockup_method#8]
@mdrudi I'm trying to implement the download of the SSI dataset, but I have found two problems:

1. The daccess module is able to download only 1 month at time also is a larger working domain is passed
2. The daccess module is able to download only file which contains a date in the format YYYYMM

The problem **1** is easy to solve, when I generate the time to check in the file name I already create a list of time but I only put the date related to the first time stamp, it is sufficient to generate all the times in the time interval

The point two can be solved using a parameter to set the time frequency (yearly, monthly, daily and so on) and then create the correct time to search in the filename.

**At this point remaining another problem, how specify to download a file that cover several years?**

**Comment by anto6715** [comment]
> At this point remaining another problem, how specify to download a file that cover several years?

To be more clear with a practice example, SSI dataset file is named:

**C3S_ERA5_WIND_Medsea_1979_2020.nc**

daccess is not able to download a file where the time is a range.
I can change the time resolution to year and generate all the time between 1979 and 2020, but in this way the procedure will try to download twice the file, because the match will be successful with two different time value.

Maybe a solution could be to check which files will be download, if a file already match a condition **SUBSTRING** + **TIME** to don't consider anymore that specific file and then download only 1 time

**Comment by mdrudi** [comment]
this is a very different and specific case : in the current implementation, this method is using a unique input file....
Maybe the better is to provide an hardcoded solution, to transfer that hardcoded file. Maybe it is reasonable to think about something better, when data are diveded by month...

**Comment by anto6715** [comment]
> this is a very different and specific case : in the current implementation, this method is using a unique input file.... Maybe the better is to provide an hardcoded solution, to transfer that hardcoded file. Maybe it is reasonable to think about something better, when data are diveded by month...

Yes is a particular case, but the important thing for daccess module is the date in the filename.
I can say that the old version on daccess has a bug, because it download (and load in memory) twice a file with a single function call if that file has two dates in the filename.
I corrected this bug (it was very simple).

Then it was sufficient to add the support to yearly date in the filename, in this way now we are able to download also this kind of dataset, or any kind of dataset that covers a time range.

The important thing is to set correctly the time frequency in according with the filename
